"""Risk Manager API — Anthropic Messages API con structured output via tool calling.

Esta API recibe trades + metrics ya calculados por el frontend (TanStack
Start / Lovable) y delega el AUDIT a Claude usando tool calling — Claude
no recalcula, solo analiza los findings y produce el email + recomendación
estructurada (12 campos).

Contract (compatible con riskmanager.functions.ts del frontend):

  POST /audit | /full | /analyze | /narrate   (los 4 son aliases)
  Headers: X-API-Key: <API_SECRET>
  Body JSON:
    {
      "account":  { accountNumber, traderName, accountType, phase,
                    accountSize, initialBalance, ... },
      "preset":   { id, name, dailyLossPercent, maxLossPercent,
                    profitTargetPercent, ... },
      "trades":   [ { ticket, symbol, side, volume, entryPrice,
                      stopLoss, profit, ... }, ... ],
      "metrics":  { totalClosedPnL, bestTradingDay,
                    consistencyPercentage, profitTargetReached,
                    maxClosedLossPercent, tradesWithoutSL, ... }
    }

  Response:
    {
      ok: True,
      data: {
        finalDecision: "PASSED" | "WARNING" | "BREACH" | "MANUAL_REVIEW",
        severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL",
        executiveSummary: str,
        confirmedBreaches: [{...}],
        estimatedBreaches: [...],
        warnings: [...],
        notEnoughData: [...],
        ruleByRuleAnalysis: [...],
        evidenceTable: [{...}],
        internalRecommendation: "APPROVE PAYOUT" | "REJECT PAYOUT" |
                                "PARTIAL APPROVAL" | "MANUAL REVIEW REQUIRED",
        emailSubject: str,
        emailBody: str
      },
      latencyMs: int,
      model: str,
      usage: {...},
      trades_dropped: int
    }

  GET /health  — sin auth, para healthchecks (no expone secrets)
"""

from __future__ import annotations

import json
import logging
import os
import random
import time
from typing import Any, Optional

import anthropic
import httpx
from fastapi import Depends, FastAPI, HTTPException, Request, Security
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.security.api_key import APIKeyHeader
from pydantic import BaseModel, Field

# ────────────────────────────────────────────────────────────────────────────
# Config
# ────────────────────────────────────────────────────────────────────────────

API_SECRET = os.environ.get("API_SECRET", "")
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
MODEL = os.environ.get("ANTHROPIC_MODEL", "claude-opus-4-7")
MAX_TOKENS = int(os.environ.get("ANTHROPIC_MAX_TOKENS", "12000"))
ANTHROPIC_TIMEOUT_SECONDS = float(os.environ.get("ANTHROPIC_TIMEOUT_SECONDS", "120"))
ANTHROPIC_MAX_RETRIES = int(os.environ.get("ANTHROPIC_MAX_RETRIES", "3"))

ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        "ALLOWED_ORIGINS",
        "http://localhost:5173,http://localhost:8080,https://lovable.dev",
    ).split(",")
    if o.strip()
]

# Trades muy grandes saturan el context window. Capamos el sample que mandamos
# al modelo y dejamos los counts en metrics — el system prompt avisa.
MAX_TRADES_IN_PROMPT = int(os.environ.get("MAX_TRADES_IN_PROMPT", "300"))

# Tamaño máximo del JSON body. Por encima rechazamos para evitar OOM en el worker.
MAX_REQUEST_BYTES = int(os.environ.get("MAX_REQUEST_BYTES", str(5 * 1024 * 1024)))

# Anti-leak: nunca permitir estos strings en emailBody, sin importar lo que
# devuelva el modelo. Si aparecen, rechazamos la respuesta y devolvemos 502.
EMAIL_FORBIDDEN_SUBSTRINGS = [
    "claude",
    "anthropic",
    "openai",
    "gpt",
    " llm",
    "ai-generated",
    "ai generated",
    "automated by",
    "this is an automated",
    "generated by ai",
    "language model",
]

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("riskmanager")

app = FastAPI(
    title="NYS Risk Manager API",
    description="Payout audit con Claude (Anthropic Messages API + tool calling)",
    version="3.1.0",
)

# CORS: orígenes desde env, headers explícitos (no wildcard) y solo POST/GET.
app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["Content-Type", "X-API-Key"],
    allow_credentials=False,
)

api_key_header = APIKeyHeader(name="X-API-Key", auto_error=True)


def require_api_key(api_key: str = Security(api_key_header)) -> str:
    if not API_SECRET:
        raise HTTPException(503, "API_SECRET not configured on server")
    if api_key != API_SECRET:
        raise HTTPException(403, "Invalid API key")
    return api_key


# ────────────────────────────────────────────────────────────────────────────
# System prompt — covers every standard prop-firm rule across program / phase
# ────────────────────────────────────────────────────────────────────────────

SYSTEM_PROMPT = """You are a senior Risk & Compliance Analyst for a proprietary trading firm. You audit a trader's MetaTrader account for payout eligibility against the firm's program rules. Your output must hold up in an institutional compliance review.

The goal is NOT to simply say "pass" or "fail". The goal is to produce a complete risk report explaining:
- Which rules were respected.
- Which rules were breached.
- Which rules require manual review.
- Which specific trades/tickets caused concern.
- How each calculation was made.
- Why a specific action should be applied: approved, warning, remove profit, partial payout reduction, breach, account closure, or disqualification.

You receive:
- Account metadata (program / phase / size / requested payout / timezone / dailyResetTime).
- Selected rule preset (the firm's per-program thresholds — the source of truth).
- A sample of parsed trades (may be capped — see "trades_total_count" and "trades_sample" in the payload).
- Deterministic metrics computed by the frontend on the FULL trade set (authoritative ground truth).
- SL/TP data per trade.
- Balance and equity if available.

# CRITICAL ANALYSIS PRINCIPLES

Be strict, precise, and evidence-based. Do not hallucinate. Do not assume facts that are not in the data or rule configuration. If data is missing, clearly mark it as missing.

Every finding must include:
- Rule name and allowed threshold from the preset.
- Observed value (with the same units as the threshold).
- Calculation method.
- Evidence (which tickets / which observation).
- Severity.
- Recommended enforcement action.
- Confidence level (CONFIRMED / ESTIMATED / NOT_ENOUGH_DATA).

# Hard rules of conduct

1. Do not invent data. Never fabricate prices, tickets, timestamps, equity, SL, TP or calculations.
2. Treat the deterministic metrics as ground truth. Explain, contextualize and present them — do not recompute them.
3. If a rule threshold is missing from the preset (e.g. preset.profitTargetPercent is null/undefined), set the rule status to NOT_ENOUGH_DATA and explain what is missing. NEVER invent or substitute an "industry standard" default.
4. Use exact tickets, symbols, timestamps, volumes, entry prices, close prices, SL, TP and P&L from the provided data — never approximate or invent these values.
5. Clearly separate confirmed breaches (from uploaded data) from estimated breaches (from heuristics like SL distance × volume).
6. If a rule cannot be evaluated from the data, set status NOT_ENOUGH_DATA or MANUAL_REVIEW.
7. Generate a professional email the admin can copy and send manually. Do not send emails automatically.
8. Use firm, professional, compliance-oriented language. No accusations without confirmed data.

# CALCULATION STANDARDS

Use precise formulas and explain them in the rule's `calculation` field.

## Daily Loss Limit
Source of truth: metrics.dailyLossAnalysis (per-day series computed by the engine).
- threshold_amount = day_start_reference × preset.dailyLossPercent / 100
  where day_start_reference = max(balance_at_day_start, equity_at_day_start)
  When equity is unavailable, use balance — flag confidence accordingly.
- breach when: lowest_intraday_equity ≤ day_start_reference − threshold_amount
  When lowest intraday equity is unavailable, fall back to closed-only realized P&L for that day and mark MANUAL_REVIEW if the result is within 10% of the limit.
- relatedTickets: every ticket that contributed to the breaching day.

## Maximum Loss (Overall Drawdown)
Source: metrics.maxLossAnalysis and metrics.maxClosedLossPercent.
- threshold_amount = initial_balance × preset.maxLossPercent / 100
- breach_threshold_balance = initial_balance − threshold_amount
- breach when: minimum observed (equity if available, else balance) ≤ breach_threshold_balance.
- Distinguish closed-only drawdown from peak-to-trough equity drawdown when both are available.

## Trailing Loss Limit (if preset includes a trailing rule)
- trailing_limit_amount = initial_balance × preset.trailingLossPercent / 100
- trailing_threshold = highest_equity_observed − trailing_limit_amount
- breach when: equity ≤ trailing_threshold
- Without a tick-by-tick equity curve, approximate from highest_observed_balance and flag confidence.

## Max Risk per Trade Idea
Source: metrics.tradeIdeaRiskAnalysis. A trade idea = trades sharing the same symbol + direction + a tight time window (default 60–300 s; respect what the engine grouped).
- risk_per_lot (BUY)  = open_price − stop_loss
- risk_per_lot (SELL) = stop_loss − open_price
- monetary_risk = risk_per_lot × lot_size × contract_size × conversion_rate
- idea_total_risk = sum(monetary_risk for trades in the idea)
- idea_risk_percent = idea_total_risk / account_balance_reference × 100
- BREACH if idea_risk_percent > preset.maxRiskPerTradeIdeaPercent.
- WARNING if 85% ≤ idea_risk_percent ≤ 100% of the threshold.
- If an idea has no SL on any leg, theoretical ex-ante risk is unbounded → set status MANUAL_REVIEW (or BREACH if the preset's prohibitedStrategies includes "no-SL high risk") with relatedTickets listing every leg. Do not claim a specific risk number.
- dataQuality = "ESTIMATED" (risk is derived from SL distance × volume, not actual fills).

## Max Exposure per Instrument
- exposure_percent = total_open_notional_or_risk_per_symbol / account_balance × 100
- For closed trades only, derive simultaneous exposure from overlapping open/close timestamps.
- BREACH if exposure_percent > preset.maxExposurePerSymbolPercent.

## Maximum Open Risk (INSTANT program ONLY — HARD BREACH)
- For account.accountType == "INSTANT", threshold = preset.maxOpenRiskPercent if present, else default 1.0 (1%).
- Total floating loss across all simultaneously open positions must never exceed the threshold. Source: metrics.openTradesExposure.
- BREACH if any moment's open-risk sum exceeds the threshold AND all relevant SLs are known.
- MANUAL_REVIEW if any moment had ≥2 simultaneously open positions and at least one had no stop loss.
- PASSED if always under threshold and all SLs are known throughout.
- For non-INSTANT accounts: include the rule with explanation="Rule applies to INSTANT program only.", status="PASSED".

## Profit Target — applies ONLY to evaluation phases (PHASE_1, PHASE_2)
- For account.phase == "LIVE": include one ruleByRuleAnalysis entry with status="PASSED", dataQuality="CONFIRMED", explanation="Not applicable on live funded accounts." Do NOT count this as a breach.
- For evaluation phases: target_amount = initial_balance × preset.profitTargetPercent / 100.
- status = "PASSED" if reached, "MANUAL_REVIEW" if not reached and trader is requesting payout, "NOT_ENOUGH_DATA" if metric is "NOT_ENOUGH_DATA".

## Minimum Trading Days
- A "trading day" is a calendar day in account.serverTimezone (reset at account.dailyResetTime) with at least one trade OPENED.
- Source: metrics.tradingDaysCount and metrics.minTradingDaysAnalysis.
- BREACH if tradingDaysCount < preset.minTradingDays.
- Flag micro-trades (very small lot size, < 1 minute holding, no SL) if the preset's policy treats them as abuse of the rule.

## Minimum Trades
- Count valid market trades only; exclude deposits, withdrawals, credits, corrections, internal adjustments.

## Consistency Rule
- threshold = preset.consistencyRulePercent.
- consistency_percent = bestTradingDayProfit / totalClosedPnL × 100, only when totalClosedPnL > 0.
- If totalClosedPnL ≤ 0 → NOT_ENOUGH_DATA (cannot evaluate consistency on a losing or break-even period).
- BREACH if consistency_percent > threshold; WARNING if within 90–100% of threshold.

## Minimum 2 Assets Rule (if configured)
- Count distinct symbols traded. If the rule requires N distinct instruments, BREACH if < N.

## Trades Without Stop Loss
- Source: metrics.tradesWithoutSL.
- WARNING if non-empty; promote to BREACH if any such trade lost > 2% of initial balance, or if preset.prohibitedStrategies includes "no-SL high risk" / "Trades without SL".
- relatedTickets MUST include the ticket numbers.

## Prohibited Strategy Patterns
Source: metrics.prohibitedPatterns + inspection of trades_sample. Default thresholds (unless preset overrides):
- Martingale: 3+ consecutive same-symbol/same-direction trades each ≥1.5× the previous volume AND each closed at a loss → WARNING; ≥5 in a row or doubled volume → BREACH.
- Grid / Position Stacking: 5+ trades on the same symbol with overlapping open windows and evenly-spaced entry prices → WARNING; identical entries pyramided → BREACH if account policy prohibits.
- Stacking (lighter): 3+ same-symbol/side trades opened within 60 s → WARNING.
- Tick scalping: median holding time < 60 s across ≥30 trades → WARNING; if the preset prohibits it and the median is < 15 s → BREACH.
- Lot-size spike: volume ≥ 3× rolling median of the trader's prior 30 trades → WARNING (BREACH if combined with no-SL).
- Hedging within account: opposing positions on the same symbol opened within 60 s → MANUAL_REVIEW.
- High-Frequency Trading: very high trades/day on the same symbol with sub-minute holds — WARNING / MANUAL_REVIEW unless explicitly prohibited.
Each detected pattern → one ruleByRuleAnalysis entry with relatedTickets listing every involved ticket.

## News Restrictions
- Evaluate ONLY if preset.newsRestrictionEnabled is true.
- If true and metrics.newsTradingFindings is present: enforce per-event windows (preset.newsMinutesBefore / preset.newsMinutesAfter) and flag any trade opened/closed inside a restricted window as BREACH.
- If true but news data is unavailable: NOT_ENOUGH_DATA with explanation="News-time data not available in this payload — requires server-side news calendar.".
- If preset.newsRestrictionEnabled is false: status="PASSED" with explanation="News restrictions are not enabled for this preset.".

## Policies that CANNOT be proven from the HTML alone
The following policies typically require data the MT statement does not carry:
- Platform exploit / latency arbitrage / spread manipulation.
- Copy trading detection (requires multi-account correlation).
- Account sharing (requires IP / device fingerprints).
- Multi-account hedging (requires cross-account correlation).
- EA usage (requires server-side logs).
For each of these, output a rule entry with status="MANUAL_REVIEW" and explanation that lists the data needed for confirmation (IP logs, device fingerprints, execution latency, cross-account correlation, trade-copier matching, server logs, tick data, liquidity data). Never call these a definitive breach without external evidence.

## Payout Eligibility
A payout is eligible when ALL of the following are true:
  1. Profit Target rule is PASSED or N/A (LIVE phase).
  2. Minimum Trading Days rule is PASSED.
  3. No CONFIRMED breaches across any of the above rules.
  4. Consistency Rule is PASSED.
  5. requestedPayout (if provided) ≤ closed P&L available.
Compute payoutEligibility as one ruleByRuleAnalysis entry.

# internalRecommendation enum mapping

Map the institutional decision to one of the existing tool-call enum values:
- "APPROVE PAYOUT" — all 5 payout-eligibility conditions PASSED, no BREACH-severity items.
- "PARTIAL APPROVAL" — most conditions PASSED but consistency or daily-loss has WARNING (firm policy allows partial), OR specific offending trades should have their profit removed (payout-reduction-recommended).
- "REJECT PAYOUT" — confirmed BREACH on a material rule, account-closure or disqualification recommended.
- "MANUAL REVIEW REQUIRED" — material rules are NOT_ENOUGH_DATA or MANUAL_REVIEW; suspicious prohibited-pattern findings without conclusive evidence.

# finalDecision and severity

- finalDecision = "BREACH" if any confirmedBreaches has status="BREACH".
- finalDecision = "WARNING" if there are warnings/estimatedBreaches but no confirmed BREACH.
- finalDecision = "MANUAL_REVIEW" if material rules are NOT_ENOUGH_DATA or MANUAL_REVIEW and the decision cannot be made.
- finalDecision = "PASSED" only when all applicable rules pass with confirmed data and there are no warnings of concern.
- severity reflects the worst rule: LOW (no findings), MEDIUM (warnings only), HIGH (one confirmed breach), CRITICAL (multiple confirmed breaches or prohibited-pattern BREACH).

# evidenceTable

Up to 30 rows. Each row is one observation supporting a finding. observation and ruleRef are mandatory; ticket/symbol/time are optional (e.g. "Minimum Trading Days" has no specific ticket — use observation="Trader logged 4 distinct trading days, below the 5-day minimum.").

# Extended optional fields (populate when relevant — UI will use them when present)

- `tradeIdeaGroups`: array of { ideaId, symbol, direction, startTime, endTime, tickets[], totalLots, estimatedTotalRiskAmount, estimatedTotalRiskPercentage, allowedRiskPercentage, status, explanation }.
- `dailyAnalysis`: array of { date, dayStartReference, dailyPnL, lowestObserved, dailyLossLimitAmount, dailyLossLimitPercent, status, affectedTickets[], explanation }.
- `prohibitedPolicyReview`: array of { policyName, status (no_evidence|suspicious|breached|manual_review_required|not_applicable), severity, evidence, affectedTickets[], explanation, dataNeededForConfirmation[] }.
- `accountSummaryExtras`: { netProfit, grossProfit, grossLoss, winningTrades, losingTrades, winRatePercent, profitFactor, largestWin, largestLoss, mostTradedSymbol, highestRiskSymbol }.
- `humanReportMarkdown`: a complete professional markdown report with the sections: Executive Summary, Account Overview, Final Decision, Rule-by-Rule Review (with limits, observed, status, calculation, affected tickets), Critical Findings, Trade-Level Evidence, Max Risk per Trade Idea Analysis, Prohibited Trading Policy Review, Data Limitations, Recommended Action.

# Email output (emailSubject + emailBody) — must be ready for the admin to copy and send without edits.

Structure for emailBody:
1. Greeting using the trader's name (e.g. "Dear {{traderName}},").
2. State that the Risk & Compliance team has completed a review of the payout request.
3. Reference the account number explicitly.
4. State the result clearly (passed / warning / breach / manual review required).
5. Explain the breached rule(s) or manual-review reason in plain language.
6. Include an Evidence section listing each relevant trade with: ticket, symbol, direction, volume, open time, close time, entry price, close price, SL, TP, P&L, allowed threshold, and actual result. Use only values present in the input data — write "N/A" when a field is missing. Format as a readable list or aligned text block (NO markdown tables, no `|` characters used as table separators, no triple backticks).
7. Briefly explain in simple language why the rule was breached or why review is required.
8. State the next step clearly: payout approved, payout rejected, partial approval, or manual review required.
9. Professional closing signed by "Risk & Compliance Team".

Email tone:
- Professional, firm, respectful, compliance-oriented.
- No accusations unless proven by uploaded data. For estimated or pattern findings, use language such as "The review identified a pattern consistent with..." or "This requires manual review...".
- No aggressive, emotional, or apologetic wording.
- Prefer phrasings like: "The review identified...", "Based on the available account data...", "The account exceeded...", "This requires manual review...".

Hard prohibitions in emailBody (case-insensitive — NEVER include any of these substrings):
"claude", "anthropic", "openai", "gpt", "llm", "ai-generated", "ai generated", "language model", "automated by", "this is an automated", "generated by ai". Do not reference any AI or automation tooling, internal reasoning, confidence scores, or provider names. Do not promise outcomes outside the stated next step.

emailSubject must be concise and reference the account number and outcome (e.g. "Payout Review – Account 12345 – Manual Review Required").

# Output contract

You respond ONLY by calling the submit_audit_result tool with valid structured output. No prose outside the tool call. Use the exact UPPER_SNAKE_CASE enum values where the schema requires them (finalDecision, severity, per-rule status / dataQuality). Populate the extended optional fields (humanReportMarkdown, tradeIdeaGroups, dailyAnalysis, prohibitedPolicyReview, accountSummaryExtras) whenever the data supports it.
"""


RULE_ANALYSIS_SCHEMA = {
    "type": "object",
    "properties": {
        "rule": {"type": "string"},
        "status": {
            "type": "string",
            "enum": ["PASSED", "WARNING", "BREACH", "MANUAL_REVIEW", "NOT_ENOUGH_DATA"],
        },
        "severity": {
            "type": "string",
            "enum": ["LOW", "MEDIUM", "HIGH", "CRITICAL"],
        },
        "dataQuality": {
            "type": "string",
            "enum": ["CONFIRMED", "ESTIMATED", "NOT_ENOUGH_DATA"],
        },
        "explanation": {"type": "string"},
        "calculation": {"type": "string"},
        "relatedTickets": {"type": "array", "items": {"type": "string"}},
        "allowed": {
            "type": "string",
            "description": "Allowed threshold for this rule (e.g. '5% / $5,000').",
        },
        "actual": {
            "type": "string",
            "description": "Actual measured result for this rule (e.g. '6.2% / $6,200').",
        },
    },
    "required": ["rule", "status", "severity", "dataQuality", "explanation"],
}

SUBMIT_AUDIT_TOOL = {
    "name": "submit_audit_result",
    "description": "Submit the structured payout audit result.",
    "input_schema": {
        "type": "object",
        "properties": {
            "finalDecision": {
                "type": "string",
                "enum": ["PASSED", "WARNING", "BREACH", "MANUAL_REVIEW"],
            },
            "severity": {
                "type": "string",
                "enum": ["LOW", "MEDIUM", "HIGH", "CRITICAL"],
            },
            "executiveSummary": {"type": "string"},
            "confirmedBreaches": {
                "type": "array",
                "items": RULE_ANALYSIS_SCHEMA,
            },
            "estimatedBreaches": {
                "type": "array",
                "items": RULE_ANALYSIS_SCHEMA,
            },
            "warnings": {"type": "array", "items": RULE_ANALYSIS_SCHEMA},
            "notEnoughData": {"type": "array", "items": RULE_ANALYSIS_SCHEMA},
            "ruleByRuleAnalysis": {
                "type": "array",
                "items": RULE_ANALYSIS_SCHEMA,
            },
            "evidenceTable": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "ticket": {"type": "string"},
                        "symbol": {"type": "string"},
                        "time": {"type": "string"},
                        "observation": {"type": "string"},
                        "ruleRef": {"type": "string"},
                    },
                    # Only observation + ruleRef are mandatory — some rules
                    # (e.g. Minimum Trading Days) have no specific ticket.
                    "required": ["observation", "ruleRef"],
                },
            },
            "internalRecommendation": {
                "type": "string",
                "enum": [
                    "APPROVE PAYOUT",
                    "REJECT PAYOUT",
                    "PARTIAL APPROVAL",
                    "MANUAL REVIEW REQUIRED",
                ],
            },
            "emailSubject": {"type": "string"},
            "emailBody": {"type": "string"},

            # Extended optional fields (populated when the data supports them).
            # The UI consumes these progressively — absence is fine.
            "humanReportMarkdown": {
                "type": "string",
                "description": "Full professional markdown report (Executive Summary, Account Overview, Rule-by-Rule Review, Critical Findings, Trade-Level Evidence, Max Risk per Trade Idea Analysis, Prohibited Trading Policy Review, Data Limitations, Recommended Action).",
            },
            "tradeIdeaGroups": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "ideaId": {"type": "string"},
                        "symbol": {"type": "string"},
                        "direction": {"type": "string", "enum": ["BUY", "SELL", "MIXED"]},
                        "startTime": {"type": "string"},
                        "endTime": {"type": "string"},
                        "tickets": {"type": "array", "items": {"type": "string"}},
                        "totalLots": {"type": "number"},
                        "estimatedTotalRiskAmount": {"type": "number"},
                        "estimatedTotalRiskPercentage": {"type": "number"},
                        "allowedRiskPercentage": {"type": "number"},
                        "status": {
                            "type": "string",
                            "enum": ["PASSED", "WARNING", "BREACH", "MANUAL_REVIEW"],
                        },
                        "explanation": {"type": "string"},
                    },
                    "required": ["ideaId", "symbol", "tickets", "status", "explanation"],
                },
            },
            "dailyAnalysis": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "date": {"type": "string"},
                        "dayStartReference": {"type": "number"},
                        "dailyPnL": {"type": "number"},
                        "lowestObserved": {"type": "number"},
                        "dailyLossLimitAmount": {"type": "number"},
                        "dailyLossLimitPercent": {"type": "number"},
                        "status": {
                            "type": "string",
                            "enum": ["PASSED", "WARNING", "BREACH", "MANUAL_REVIEW", "NOT_ENOUGH_DATA"],
                        },
                        "affectedTickets": {"type": "array", "items": {"type": "string"}},
                        "explanation": {"type": "string"},
                    },
                    "required": ["date", "status", "explanation"],
                },
            },
            "prohibitedPolicyReview": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "policyName": {"type": "string"},
                        "status": {
                            "type": "string",
                            "enum": [
                                "NO_EVIDENCE",
                                "SUSPICIOUS",
                                "BREACHED",
                                "MANUAL_REVIEW_REQUIRED",
                                "NOT_APPLICABLE",
                            ],
                        },
                        "severity": {
                            "type": "string",
                            "enum": ["NONE", "LOW", "MEDIUM", "HIGH", "CRITICAL"],
                        },
                        "evidence": {"type": "string"},
                        "affectedTickets": {"type": "array", "items": {"type": "string"}},
                        "explanation": {"type": "string"},
                        "dataNeededForConfirmation": {"type": "array", "items": {"type": "string"}},
                    },
                    "required": ["policyName", "status", "explanation"],
                },
            },
            "accountSummaryExtras": {
                "type": "object",
                "properties": {
                    "netProfit": {"type": "number"},
                    "grossProfit": {"type": "number"},
                    "grossLoss": {"type": "number"},
                    "winningTrades": {"type": "integer"},
                    "losingTrades": {"type": "integer"},
                    "winRatePercent": {"type": "number"},
                    "profitFactor": {"type": "number"},
                    "largestWin": {"type": "number"},
                    "largestLoss": {"type": "number"},
                    "mostTradedSymbol": {"type": "string"},
                    "highestRiskSymbol": {"type": "string"},
                },
            },
        },
        "required": [
            "finalDecision",
            "severity",
            "executiveSummary",
            "confirmedBreaches",
            "estimatedBreaches",
            "warnings",
            "notEnoughData",
            "ruleByRuleAnalysis",
            "evidenceTable",
            "internalRecommendation",
            "emailSubject",
            "emailBody",
        ],
    },
}


# Pre-computed enum sets for output validation
_FINAL_DECISIONS = {"PASSED", "WARNING", "BREACH", "MANUAL_REVIEW"}
_SEVERITIES = {"LOW", "MEDIUM", "HIGH", "CRITICAL"}
_RULE_STATUSES = {"PASSED", "WARNING", "BREACH", "MANUAL_REVIEW", "NOT_ENOUGH_DATA"}
_DATA_QUALITIES = {"CONFIRMED", "ESTIMATED", "NOT_ENOUGH_DATA"}
_RECOMMENDATIONS = {
    "APPROVE PAYOUT",
    "REJECT PAYOUT",
    "PARTIAL APPROVAL",
    "MANUAL REVIEW REQUIRED",
}


# ────────────────────────────────────────────────────────────────────────────
# Request / response models
# ────────────────────────────────────────────────────────────────────────────


class AuditRequest(BaseModel):
    """Frontend envía este shape. Aceptamos cualquier campo extra para forward-compat."""

    account: dict[str, Any] = Field(..., description="AccountMetadata")
    preset: dict[str, Any] = Field(..., description="RulePreset")
    trades: list[dict[str, Any]] = Field(default_factory=list)
    metrics: dict[str, Any] = Field(default_factory=dict)

    class Config:
        extra = "allow"


# ────────────────────────────────────────────────────────────────────────────
# Smart trade sampling — preserve flagged trades, fill with uniform sample
# ────────────────────────────────────────────────────────────────────────────


def _truncate_trades(
    trades: list[dict], metrics: dict[str, Any]
) -> tuple[list[dict], int]:
    """Select up to MAX_TRADES_IN_PROMPT trades, preserving ones the engine flagged.

    Strategy:
      1. Build a "must keep" set from metrics: tradesWithoutSL, lotSizeSpikes,
         largestLosingTradeTicket, shortDurationTrades, and any ticket inside
         tradeIdeaRiskAnalysis / stackedTrades / prohibitedPatterns.
      2. Always keep the first and last trade (boundaries).
      3. Fill the remainder with a uniform-by-index sample from the unflagged
         population, to preserve temporal distribution.

    Returns (sampled_list, dropped_count).
    """
    n = len(trades)
    if n <= MAX_TRADES_IN_PROMPT:
        return trades, 0

    must_keep: set[str] = set()

    def _add(values: Any) -> None:
        if values is None:
            return
        if isinstance(values, str):
            must_keep.add(values)
            return
        if isinstance(values, (list, tuple, set)):
            for v in values:
                if isinstance(v, str):
                    must_keep.add(v)
                elif isinstance(v, dict):
                    t = v.get("ticket") or v.get("orderId")
                    if isinstance(t, str):
                        must_keep.add(t)
                    tickets = v.get("tickets") or v.get("relatedTickets")
                    if isinstance(tickets, list):
                        for tt in tickets:
                            if isinstance(tt, str):
                                must_keep.add(tt)

    _add(metrics.get("tradesWithoutSL"))
    _add(metrics.get("shortDurationTrades"))
    _add(metrics.get("lotSizeSpikes"))
    _add(metrics.get("stackedTrades"))
    _add(metrics.get("tradeIdeaRiskAnalysis"))
    _add(metrics.get("prohibitedPatterns"))
    _add(metrics.get("largestLosingTradeTicket"))

    kept_indices: set[int] = set()
    for i, t in enumerate(trades):
        ticket = str(t.get("ticket") or t.get("orderId") or "")
        if ticket and ticket in must_keep:
            kept_indices.add(i)

    # Always keep boundaries.
    kept_indices.add(0)
    kept_indices.add(n - 1)

    remaining = MAX_TRADES_IN_PROMPT - len(kept_indices)
    if remaining > 0:
        unflagged_indices = [i for i in range(n) if i not in kept_indices]
        if unflagged_indices:
            step = max(1, len(unflagged_indices) / remaining)
            for j in range(remaining):
                idx = int(j * step)
                if idx < len(unflagged_indices):
                    kept_indices.add(unflagged_indices[idx])

    sorted_idx = sorted(kept_indices)
    sampled = [trades[i] for i in sorted_idx]
    return sampled, n - len(sampled)


# ────────────────────────────────────────────────────────────────────────────
# Anthropic call with timeout + retries
# ────────────────────────────────────────────────────────────────────────────


def _build_client() -> anthropic.Anthropic:
    return anthropic.Anthropic(
        api_key=ANTHROPIC_API_KEY,
        timeout=httpx.Timeout(ANTHROPIC_TIMEOUT_SECONDS, connect=10.0),
        max_retries=0,  # we implement retry ourselves to log + backoff cleanly
    )


def _call_anthropic_with_retry(client: anthropic.Anthropic, **kwargs: Any):
    """Call client.messages.create with exponential backoff on 429/5xx/overload.

    Raises the last error if all attempts fail. 4xx other than 429 are not
    retried.
    """
    last_err: Optional[BaseException] = None
    for attempt in range(ANTHROPIC_MAX_RETRIES):
        try:
            return client.messages.create(**kwargs)
        except anthropic.RateLimitError as e:
            last_err = e
            wait = (2**attempt) + random.random()
            log.warning(
                "Anthropic 429 rate limit (attempt %d/%d), retrying in %.1fs",
                attempt + 1,
                ANTHROPIC_MAX_RETRIES,
                wait,
            )
            time.sleep(wait)
        except anthropic.APIStatusError as e:
            last_err = e
            if e.status_code in (500, 502, 503, 504, 529):
                wait = (2**attempt) + random.random()
                log.warning(
                    "Anthropic %d (attempt %d/%d), retrying in %.1fs",
                    e.status_code,
                    attempt + 1,
                    ANTHROPIC_MAX_RETRIES,
                    wait,
                )
                time.sleep(wait)
                continue
            raise
        except anthropic.APIConnectionError as e:
            last_err = e
            wait = (2**attempt) + random.random()
            log.warning(
                "Anthropic connection error (attempt %d/%d), retrying in %.1fs: %s",
                attempt + 1,
                ANTHROPIC_MAX_RETRIES,
                wait,
                type(e).__name__,
            )
            time.sleep(wait)
    assert last_err is not None
    raise last_err


# ────────────────────────────────────────────────────────────────────────────
# Output validation
# ────────────────────────────────────────────────────────────────────────────


def _validate_rule_item(item: Any, path: str) -> Optional[str]:
    if not isinstance(item, dict):
        return f"{path}: not an object"
    for required in ("rule", "status", "severity", "dataQuality", "explanation"):
        if required not in item:
            return f"{path}: missing field '{required}'"
    if item["status"] not in _RULE_STATUSES:
        return f"{path}.status: invalid value '{item['status']}'"
    if item["severity"] not in _SEVERITIES:
        return f"{path}.severity: invalid value '{item['severity']}'"
    if item["dataQuality"] not in _DATA_QUALITIES:
        return f"{path}.dataQuality: invalid value '{item['dataQuality']}'"
    return None


def validate_audit_output(data: dict) -> Optional[str]:
    """Return None if valid, otherwise a short error string."""
    if not isinstance(data, dict):
        return "audit result is not an object"

    required_top = [
        "finalDecision",
        "severity",
        "executiveSummary",
        "confirmedBreaches",
        "estimatedBreaches",
        "warnings",
        "notEnoughData",
        "ruleByRuleAnalysis",
        "evidenceTable",
        "internalRecommendation",
        "emailSubject",
        "emailBody",
    ]
    for f in required_top:
        if f not in data:
            return f"missing top-level field '{f}'"

    if data["finalDecision"] not in _FINAL_DECISIONS:
        return f"finalDecision: invalid value '{data['finalDecision']}'"
    if data["severity"] not in _SEVERITIES:
        return f"severity: invalid value '{data['severity']}'"
    if data["internalRecommendation"] not in _RECOMMENDATIONS:
        return (
            "internalRecommendation: invalid value "
            f"'{data['internalRecommendation']}'"
        )

    for arr in (
        "confirmedBreaches",
        "estimatedBreaches",
        "warnings",
        "notEnoughData",
        "ruleByRuleAnalysis",
    ):
        items = data.get(arr)
        if not isinstance(items, list):
            return f"{arr}: not an array"
        for i, item in enumerate(items):
            err = _validate_rule_item(item, f"{arr}[{i}]")
            if err:
                return err

    if not isinstance(data["evidenceTable"], list):
        return "evidenceTable: not an array"
    for i, row in enumerate(data["evidenceTable"]):
        if not isinstance(row, dict):
            return f"evidenceTable[{i}]: not an object"
        if "observation" not in row or "ruleRef" not in row:
            return f"evidenceTable[{i}]: must include 'observation' and 'ruleRef'"

    # Anti-leak: never let provider/automation references reach the trader.
    body_lower = str(data.get("emailBody") or "").lower()
    for forbidden in EMAIL_FORBIDDEN_SUBSTRINGS:
        if forbidden in body_lower:
            return f"emailBody contains forbidden phrase '{forbidden.strip()}'"
    if "|---" in body_lower or "| ---" in body_lower:
        return "emailBody contains markdown table syntax"

    return None


# ────────────────────────────────────────────────────────────────────────────
# Audit handler
# ────────────────────────────────────────────────────────────────────────────


def run_audit(req: AuditRequest) -> dict:
    """Llama a Claude con el contexto, fuerza tool call, retorna structured output."""
    if not ANTHROPIC_API_KEY:
        raise HTTPException(503, "ANTHROPIC_API_KEY not configured on server")

    client = _build_client()

    trades_for_prompt, dropped = _truncate_trades(req.trades, req.metrics)
    sampling_note = ""
    if dropped:
        sampling_note = (
            f"\n\nNOTE: trades_sample was reduced from {len(req.trades)} total "
            f"down to {len(trades_for_prompt)} entries while preserving every "
            "ticket flagged by metrics (no-SL, lot spikes, prohibited-pattern "
            "clusters, largest losing trade, short-duration trades). Counts "
            "and metrics are computed on the FULL set; use `metrics` as ground "
            "truth for totals."
        )

    user_payload = {
        "account": req.account,
        "preset": req.preset,
        "metrics": req.metrics,
        "trades_sample": trades_for_prompt,
        "trades_total_count": len(req.trades),
    }

    user_content = (
        "Analyze the following payout review request and submit the structured "
        f"result by calling submit_audit_result.{sampling_note}\n\n"
        f"```json\n{json.dumps(user_payload, indent=2, default=str)}\n```"
    )

    # Cache the static SYSTEM_PROMPT — cuts input cost ~80% on repeat calls.
    system_blocks = [
        {
            "type": "text",
            "text": SYSTEM_PROMPT,
            "cache_control": {"type": "ephemeral"},
        }
    ]

    started = time.time()
    try:
        message = _call_anthropic_with_retry(
            client,
            model=MODEL,
            max_tokens=MAX_TOKENS,
            system=system_blocks,
            tools=[SUBMIT_AUDIT_TOOL],
            tool_choice={"type": "tool", "name": "submit_audit_result"},
            messages=[{"role": "user", "content": user_content}],
        )
    except anthropic.RateLimitError:
        log.exception("Anthropic rate limit exceeded after retries")
        raise HTTPException(503, "Risk Manager service is overloaded. Try again shortly.")
    except anthropic.APIStatusError as e:
        log.exception(
            "Anthropic API error after retries: status=%s",
            getattr(e, "status_code", "?"),
        )
        raise HTTPException(
            502, "Risk Manager upstream is currently unavailable. Try again shortly."
        )
    except anthropic.APIConnectionError:
        log.exception("Could not reach Anthropic API after retries")
        raise HTTPException(504, "Risk Manager upstream connection failed.")
    except Exception:
        log.exception("Unexpected error calling Anthropic")
        raise HTTPException(500, "Risk Manager internal error.")

    latency_ms = int((time.time() - started) * 1000)

    # Validate stop_reason — anything other than tool_use means the output is
    # likely truncated or malformed.
    stop_reason = getattr(message, "stop_reason", None)
    if stop_reason == "max_tokens":
        log.warning("Anthropic stop_reason=max_tokens — output likely truncated")
        raise HTTPException(
            502,
            "Risk Manager produced a truncated response. Increase ANTHROPIC_MAX_TOKENS "
            "or reduce trade volume.",
        )

    tool_block = next(
        (b for b in message.content if getattr(b, "type", None) == "tool_use"),
        None,
    )
    if tool_block is None:
        log.warning(
            "No tool_use block in response. stop_reason=%s", stop_reason
        )
        raise HTTPException(
            502,
            "Risk Manager did not return a structured audit. Please retry.",
        )

    audit = tool_block.input
    if not isinstance(audit, dict):
        raise HTTPException(502, "Risk Manager returned a non-object audit payload.")

    err = validate_audit_output(audit)
    if err:
        log.warning("Audit output validation failed: %s", err)
        raise HTTPException(
            502, f"Risk Manager produced an invalid audit payload: {err}"
        )

    return {
        "ok": True,
        "data": audit,
        "latencyMs": latency_ms,
        "model": MODEL,
        "usage": {
            "input_tokens": getattr(message.usage, "input_tokens", 0),
            "output_tokens": getattr(message.usage, "output_tokens", 0),
            "cache_creation_input_tokens": getattr(
                message.usage, "cache_creation_input_tokens", 0
            ),
            "cache_read_input_tokens": getattr(
                message.usage, "cache_read_input_tokens", 0
            ),
        },
        "trades_dropped": dropped,
    }


# ────────────────────────────────────────────────────────────────────────────
# Endpoints
# ────────────────────────────────────────────────────────────────────────────


@app.get("/health")
def health() -> dict:
    return {
        "status": "ok",
        "service": "risk-manager-api",
        "version": "3.1.0",
        "configured": {
            "anthropic_key": bool(ANTHROPIC_API_KEY),
            "api_secret": bool(API_SECRET),
            "model": MODEL,
        },
    }


@app.post("/audit", dependencies=[Depends(require_api_key)])
def audit(req: AuditRequest) -> dict:
    return run_audit(req)


@app.post("/analyze", dependencies=[Depends(require_api_key)])
def analyze(req: AuditRequest) -> dict:
    return run_audit(req)


@app.post("/full", dependencies=[Depends(require_api_key)])
def full(req: AuditRequest) -> dict:
    return run_audit(req)


@app.post("/narrate", dependencies=[Depends(require_api_key)])
def narrate(req: AuditRequest) -> dict:
    return run_audit(req)


# Body size cap — reject oversized payloads before parsing.
@app.middleware("http")
async def body_size_guard(request: Request, call_next):
    cl = request.headers.get("content-length")
    if cl is not None:
        try:
            n = int(cl)
            if n > MAX_REQUEST_BYTES:
                return JSONResponse(
                    status_code=413,
                    content={
                        "ok": False,
                        "error": (
                            f"Request body too large ({n} bytes, limit "
                            f"{MAX_REQUEST_BYTES})."
                        ),
                        "status": 413,
                    },
                )
        except ValueError:
            pass
    return await call_next(request)


# Logging middleware ligero — útil en Railway para ver latencias
@app.middleware("http")
async def log_requests(request: Request, call_next):
    started = time.time()
    response = await call_next(request)
    duration_ms = int((time.time() - started) * 1000)
    log.info(
        "%s %s → %s (%dms)",
        request.method,
        request.url.path,
        response.status_code,
        duration_ms,
    )
    return response


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    """Format errors to match the riskmanager.functions.ts client expectations."""
    return JSONResponse(
        status_code=exc.status_code,
        content={
            "ok": False,
            "error": exc.detail,
            "status": exc.status_code,
        },
    )
